# Generated by Django 3.0.7 on 2020-06-26 10:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dasktasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='documents/')),
                ('sum_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dasktasks.DaskTask')),
            ],
        ),
    ]
