# Generated by Django 3.0.7 on 2020-06-24 21:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dasktasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CsvDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(editable=False, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SumAmountEuroTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('csv_document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oaze.CsvDocument')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dasktasks.DaskTask')),
            ],
        ),
    ]
