# Generated by Django 3.0.7 on 2020-06-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oaze', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvdocument',
            name='file',
            field=models.FileField(upload_to=''),
        ),
    ]
