# Generated by Django 3.0.7 on 2020-06-26 10:00

from django.db import migrations, models
import django.utils.timezone
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaskTask',
            fields=[
                ('task_key', models.CharField(max_length=512, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=32, null=True)),
                ('result', picklefield.fields.PickledObjectField(editable=False, null=True)),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField(null=True)),
                ('duration', models.PositiveIntegerField(null=True)),
            ],
        ),
    ]
