# Generated by Django 3.0.7 on 2020-06-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dasktasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dasktask',
            old_name='duration',
            new_name='duration_ms',
        ),
    ]
