version: '3'
services:
  djangoapp:
    build: .
    volumes:
    - static-content:/static
    entrypoint:
    - /bin/sh
    - -c
    command:
    -  python manage.py collectstatic --noinput && gunicorn -b :8000 api.wsgi

  nginx:
    image: nginx
    volumes:
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
    - static-content:/static
    ports:
    - "8000:80"
    - "8001:8001"
    depends_on:
    - djangoapp

volumes:
  static-content:

